# PATH
export PATH=$HOME/.local/bin:/usr/local/bin:$PATH
export PATH=$PATH:$HOME/.npm-global/bin
export PATH=$PATH:$HOME/.config/composer/vendor/bin

# Lines configured by zsh-newuser-install
HISTFILE=~/.histfile
HISTSIZE=1000
SAVEHIST=1000
setopt beep nomatch notify
bindkey -e
# End of lines configured by zsh-newuser-install

# Add folders to zsh fpath
fpath=(~/.zsh/completions /usr/share/zsh/vendor-completions $fpath)

# The following lines were added by compinstall
zstyle :compinstall filename '/home/muhammad/.zshrc'

autoload -Uz compinit
compinit
# End of lines added by compinstall

# Custom
# Print empty line after every prompt, except the first
precmd() {
    precmd() {
        echo ""
    }
}

# Plugins
[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh
source /usr/share/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh
source /usr/share/zsh-autosuggestions/zsh-autosuggestions.zsh

# Variables
export EDITOR='nvim'
export FZF_DEFAULT_COMMAND='rg --files --follow --hidden --ignore-file "/home/muhammad/workspace/dotfiles/.fzfignore"'
export FZF_CTRL_T_COMMAND="$FZF_DEFAULT_COMMAND"
export FZF_DEFAULT_OPTS='--layout=reverse --info=inline'

# Aliases
alias yarn='yarnpkg'
alias ls='lsd --group-dirs first'
alias tree='lsd --tree'
alias bat='bat --style numbers --theme ansi-dark'
alias cat='bat --paging never'
alias less='bat'
alias vim='nvim'
alias protonvpn='sudo protonvpn'
alias pvpn='sudo protonvpn'
alias code='codium'

# Load dircolors
test -r "~/.dir_colors" && eval $(dircolors ~/.dir_colors)

# Load Spaceship ZSH theme
eval "$(starship init zsh)"
